# Site settings
title: "Photons are Friends"
# email: jacob@jacobtomlinson.co.uk
description: "Notes on optics and related fields"
baseurl: ""
url: "https://photonsarefriends.com"
title_description: "(Not food)<p></p>Notes on optics, electronics, mechanics, software, modeling, instrument control, and everything else that comes up in science and engineering."
# title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
title_image: headshot.jpg
# google_analytics: "UA-20365477-4"
# disqus_account: cartenoire
github_repository: https://github.com/danieldmulkey/danieldmulkey.github.io
# addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
# twitter_username: _jacobtomlinson
github_username: danieldmulkey
# instagram_username:
# reddit_username:
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# xing_link:
# facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by Daniel Mulkey"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/danieldmulkey\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
